# Generated by Django 3.1.1 on 2020-12-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_auto_20201220_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='أمانة')),
                ('slug', models.SlugField(editable=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state', verbose_name='الولاية')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='القطاع')),
                ('slug', models.SlugField(editable=False)),
                ('hquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.hquarter', verbose_name='الرئاسة')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='المكتب')),
                ('slug', models.SlugField(editable=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.sector', verbose_name='القطاع')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
